#!/bin/bash
cd /var/named/chroot/var/named/
chown named.named /var/named/chroot/var/named/
logger "Updating DNS from ldap..."
/usr/bin/sudo -u named /usr/local/bin/ldap2dns -D "cn=px2.azko.fr,dc=azko,dc=fr" -w 21wyisey -b "ou=domains,dc=azko,dc=fr" -o bind -h localhost
#modify the named.zones file, as named doesn't like the comment!
cat named.zones | grep -v "^; Auto" > named.zones.corrected
logger "Updated DNS from ldap"
cat named.zones | sed 's/file "/file "internal\./' > named.internal.zones
#suppression des zones internal
for i in $(find /var/named/chroot/var/named -name "internal.*.db")
do
    rm $i -f
done
#génération des fichiers internal
for i in $(find /var/named/chroot/var/named -name "*.db")
do
    cat $i | sed 's/145.239.103.216/192.168.200.2/' | sed 's/178.32.130.26/192.168.200.2/' | sed 's/5.196.207.219/192.168.200.2/' | sed 's/145.239.103.217/192.168.200.8/' > /var/named/chroot/var/named/internal.$(basename $i)
done
/bin/systemctl reload named-chroot.service
chown named:named /var/named/chroot/var/named/*
